name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest]
        include:
          # non-matrix listed runs (python 3.6 is not supported with ubuntu-latest).
          - python: 3.6
            os: ubuntu-20.04
            tox_env: "py36"
          - python: 3.6
            os: windows-latest
            tox_env: "py36"
          - python: "3.7"
            tox_env: "py37"
          - python: "3.8"
            tox_env: "py38"
          - python: "3.9"
            tox_env: "py39"
          - python: "3.10"
            tox_env: "py310"
        exclude:
          - python: "3.6"
            os: "windows-latest"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses:  actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}
